const topicArr:Array<object>=[
    {
        ClassA:"试题管理",
        ClassB:[
            {
                branchNmae:"添加试题",
                branchId:"qw",
                branchUrl:"/main/addtest"
            },{
                branchNmae:"试题分类",
                branchId:"qweq",
                branchUrl:"/main/testclass"
            },{
                branchNmae:"查看试题",
                branchId:"qwqw",
                branchUrl:"/main/locktest"
            }
        ]
    },
    {
        ClassA:"用户管理",
        ClassB:[
            {
                branchNmae:"添加用户",
                branchId:"qwq",
                branchUrl:"/main/adduser"
            },{
                branchNmae:"用户展示",
                branchId:"qeew",
                branchUrl:"/main/userdisplay"
            }
        ]
    },{
        ClassA:"考试管理",
        ClassB:[
            {
                branchNmae:"添加考试",
                branchId:"qwwq",
                branchUrl:"/main/addexam"
            },{
                branchNmae:"试卷列表",
                branchId:"qwleqw",
                branchUrl:"/main/examlist"
            }
        ]
    },{
        ClassA:"班级管理",
        ClassB:[
            {
                branchNmae:"班级管理",
                branchId:"qweqw",
                branchUrl:"/main/classes"
            },{
                branchNmae:"教室管理",
                branchId:"qwtewr",
                branchUrl:"/main/classroom"
            },{
                branchNmae:"学生管理",
                branchId:"qterw",
                branchUrl:"/main/study"
            }
        ]
    },{
        ClassA:"阅卷管理",
        ClassB:[
            {
                branchNmae:"待批班级",
                branchId:"qertw",
                branchUrl:"/main/waitclass"
            }
        ]
    }
]
export default topicArr;